### ISSUE TITLE
DAGs are in queue and not running. Issue with SQS connectivity

### ISSUE THREAD

**Issue by DevOpsAirflow** [villasv/turbine#94] opened 2019-03-01 07:42 UTC
1) deployed CFT succesfully 2) All 3 servers are running state and able to access GUI
3) When I try to schedule DAG its waiting in Queue status. 4) Create SQS end points and i see connectivity from instances to RDS, SQS .and S3

Here I am attaching the errors I am seeing

**cat /tmp/env.sh**
cat /tmp/env.sh 
export AWS_DEFAULT_REGION=us-east-1
export AIRFLOW_HOME=/airflow
export AIRFLOW__CORE__EXECUTOR=CeleryExecutor
export AIRFLOW__CORE__LOAD_EXAMPLES=True
export TURBINE__CORE__LOAD_DEFAULTS=True
export AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://airflow:Airflow1234@id2te7f2x0c8cg.clsyc1ah81mk.us-east-1.rds.amazonaws.com/airflow
export AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER=s3://ipdv-airflow-part-logs
export AIRFLOW__CORE__REMOTE_LOGGING=True
export AIRFLOW__WEBSERVER__BASE_URL=http://10.202.9.xx:8080
export AIRFLOW__WEBSERVER__WEB_SERVER_PORT=8080
export AIRFLOW__CELERY__BROKER_URL=sqs://
export AIRFLOW__CELERY__DEFAULT_QUEUE=ipdv-airflow-Tasks-HQXYR0N3BQO7
export AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:Airflow1111@id2te7f2x0c8cg.clsyc1ah81mk.us-east-1.rds.amazonaws.com/airflow
export AIRFLOW__CELERY__WORKER_CONCURRENCY=1
export AIRFLOW__CELERY_BROKER_TRANSPORT_OPTIONS__REGION=us-east-1
export TURBINE_MACHINE=WORKER

**worker error**

Mar 01 07:16:32 ip-10-202-9-37.ec2.internal turbine[5032]: [2019-03-01 07:16:32,486: INFO/MainProcess] Starting new HTTP connection (1): 169.254.169.254
Mar 01 07:16:32 ip-10-202-9-37.ec2.internal turbine[5032]: [2019-03-01 07:16:32,488: INFO/MainProcess] Starting new HTTP connection (1): 169.254.169.254
Mar 01 07:16:32 ip-10-202-9-37.ec2.internal turbine[5032]: [2019-03-01 07:16:32,499: INFO/MainProcess] Starting new HTTPS connection (1): queue.amazonaws.com
Mar 01 07:17:33 ip-10-202-9-37.ec2.internal turbine[5032]: [2019-03-01 07:17:33,040: INFO/MainProcess] Starting new HTTPS connection (2): queue.amazonaws.com
Mar 01 07:18:34 ip-10-202-9-37.ec2.internal turbine[5032]: [2019-03-01 07:18:34,110: INFO/MainProcess] Starting new HTTPS connection (3): queue.amazonaws.com
Mar 01 07:19:34 ip-10-202-9-37.ec2.internal turbine[5032]: [2019-03-01 07:19:34,782: INFO/MainProcess] Starting new HTTPS connection (4): queue.amazonaws.com
Mar 01 07:20:36 ip-10-202-9-37.ec2.internal turbine[5032]: [2019-03-01 07:20:36,185: INFO/MainProcess] Starting new HTTPS connection (5): queue.amazonaws.com
Mar 01 07:21:36 ip-10-202-9-37.ec2.internal turbine[5032]: [2019-03-01 07:21:36,216: ERROR/MainProcess] consumer: Cannot connect to sqs://localhost//: HTTPSConnectionPool(host='queue.amazonaws.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPSConnection object at 0x7f1dacdce470>, 'Connection to queue.amazonaws.com timed out. (connect timeout=60)')).
Mar 01 07:21:36 ip-10-202-9-37.ec2.internal turbine[5032]: Trying again in 8.00 seconds...
Mar 01 07:21:44 ip-10-202-9-37.ec2.internal turbine[5032]: [2019-03-01 07:21:44,230: INFO/MainProcess] Starting new HTTP connection (1): 169.254.169.254
Mar 01 07:21:44 ip-10-202-9-37.ec2.internal turbine[5032]: [2019-03-01 07:21:44,232: INFO/MainProcess] Starting new HTTP connection (1): 169.254.169.254

**cloud-init-output.log**

+ /opt/aws/bin/cfn-init -v --region us-east-1 --stack ipdv-airflow-partha --resource Meta
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 884, in emit
    stream.write(fs % msg.encode("UTF-8"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 49: ordinal not in range(128)
Logged from file util.py, line 476
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 884, in emit
    stream.write(fs % msg.encode("UTF-8"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 71: ordinal not in range(128)
Logged from file util.py, line 476
+ /opt/aws/bin/cfn-signal -e 0 --region us-east-1 --stack ipdv-airflow-partha --resource AirflowWebserver
ValidationError: Stack arn:aws:cloudformation:us-east-1:393566551251:stack/ipdv-airflow-partha/e644fb50-3be9-11e9-a877-0a30b495b19a is in CREATE_COMPLETE state and cannot be signaled
Mar 01 06:32:34 cloud-init[3560]: util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-001 [1]
Mar 01 06:32:34 cloud-init[3560]: cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
Mar 01 06:32:34 cloud-init[3560]: util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
Cloud-init v. 18.2-72.amzn2.0.6 finished at Fri, 01 Mar 2019 06:32:34 +0000. Datasource DataSourceEc2.  Up 274.52 seconds

**cfn-hup.log**

2019-03-01 06:37:28,019 [ERROR] Exception caught while running hook cfn-auto-reloader-hook
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/update_hooks.py", line 586, in process
    self._process_hook(hook, metadata)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/update_hooks.py", line 594, in _process_hook
    new_data = self._retrieve_path_data(hook.path)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/update_hooks.py", line 670, in _retrieve_path_data
    self._resource_cache[logical_id] = self.client.describe_stack_resource(logical_id, self.stack_name)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/util.py", line 202, in _retry
    raise last_error
RemoteError: [Errno None]

**Comment by villasv** [comment] 2019-03-01 10:00
Hi @DevOpsAirflow, thanks for the detailed report!

> When I try to schedule DAG its waiting in Queue status

OK, so just to confirm, they're gray in the UI? And there are messages in the SQS queue?
If so, then the scheduler and webserver are working fine, the worker is the only one not working properly.

Your Environment file looks correct, so we'll start by investigating those error logs.

First things first, Amazon SQS is an Internet-based service. To connect to the Amazon SQS Endpoint (sqs.us-east-1.amazonaws.com), the Amazon EC2 instance *usually* requires access to the Internet. You mentioned that you removed the Internet Gateway, but are you providing some other mean for the EC2 machines to connect to the Internet?

If you can't give them Internet access, you might try setting up a VPC endpoint for that queue: https://aws.amazon.com/about-aws/whats-new/2018/12/amazon-sqs-vpc-endpoints-aws-privatelink/

But I'm afraid the instance needs the Internet to complete initialization, like installing the code deploy agent, so my recommendation is that you provide Internet access to the entire subnet.

**Comment by DevOpsAirflow** [comment] 2019-03-01 13:35
I do not see messages in queue. In the GUI it’s are in Queue status and dag
is going to pause status. I ran airflow unpause command but still it’s not
processing.  I see error. Https connection to. ://local host error which I
pasted. My guess is scheduler is not putting messages in SQS. I checked
cloudwatcj and lambda and both config looks good

**Comment by villasv** [comment] 2019-03-01 13:58
You'll keep seeing that error because this is the critical point:

> First things first, Amazon SQS is an Internet-based service. To connect to the Amazon SQS Endpoint (sqs.us-east-1.amazonaws.com), the Amazon EC2 instance _usually_ requires access to the Internet. You mentioned that you removed the Internet Gateway, but are you providing some other mean for the EC2 machines to connect to the Internet?
>
> If you can't give them Internet access, you might try setting up a VPC endpoint for that queue: https://aws.amazon.com/about-aws/whats-new/2018/12/amazon-sqs-vpc-endpoints-aws-privatelink/
>
> But I'm afraid the instance needs the Internet to complete initialization, like installing the code deploy agent, so my recommendation is that you provide Internet access to the entire subnet.

**Comment by DevOpsAirflow** [comment] 2019-03-01 14:03
Yes I set proxy and also I set end points. I guess scheduler will put the
message in SQS and worker will consume correct ?  I am able to run Aws SQS
cli commands from all 3 servers.  Why it’s showing SQS://localhost/. One
more thing I do not have any public IPs all I have is private IPs because
this is within our network.

**Comment by villasv** [comment] 2019-03-01 14:28
> I guess scheduler will put the message in SQS and worker will consume correct ?

Yes.

> I am able to run Aws SQS cli commands from all 3 servers.

The stack currently may require Internet access for multiple other reasons, so I'm not sure that's enough.

> Why it’s showing SQS://localhost/

Your worker is failing to connect to SQS. It's either because of lack of Internet access or misconfigured environment.

**Comment by villasv** [comment] 2019-03-01 14:37
Can you just provide me you modified template? I'll try to reproduce the issue.

**Comment by DevOpsAirflow** [comment] 2019-03-04 04:35
Hi Victor,

Did you find any thing? I see i am able to run SQS cli commands from all 3
servers. In the GUI DAGS are in queued status and I do not see anything in
SQS. queued means these are stuck in scheduler? Where can i see these in
scheduler server?

Do you want me to try any old version of templates which you have for this?

Thanks

**Comment by villasv** [comment] 2019-03-04 13:54
> Did you find any thing?

There's no way I can find what's wrong with your stack because I can't reproduce the modifications you made. Are you modifying the stack using CloudFormation or just using the Console?

> Do you want me to try any old version of templates which you have for this?

I don't think this would help, there's apparently nothing wrong with the stack as it is.

**Comment by villasv** [comment] 2019-03-04 14:00
> In the GUI DAGS are in queued status and I do not see anything in SQS.

One possible reason is that you started an Airflow scheduler service incorrectly (e.g. in LocalExecutor mode, the default) and it sent those messages to its internal queue instead of SQS.

**Comment by villasv** [comment] 2019-03-08 12:46
@DevOpsAirflow can you provide a minimal working example for me to reproduce the problem?

If not, I'll be closing the issue because I can't tell what's wrong with your deployment.

**Comment by villasv** [comment] 2019-05-11 01:04
Closing as I could not reproduce and it went inactive.

**Closed as completed by villasv** 2019-05-11 01:04 UTC
Labels: wontfix
