### ISSUE TITLE
The Launch Stack option fails to create the stack

### ISSUE THREAD

**Issue by Monikatak** [villasv/turbine#156] opened 2020-03-11 17:57 UTC
```
The Launch Stack option fails to create the stack
The following resource(s) failed to create: [Database, LogsBucket, EfsFileSystem, DeploymentsBucket]. 
```

**Comment by villasv** [comment] 2020-03-12 13:51
Hi @Monikatak, thanks for reporting. Could you provide further details? Perhaps the CloudFormation event that describes which error caused the creation failure?

Also, it might help if I know which region you attempted to deploy.

**Comment by bayarmunkh** [comment] 2020-03-12 14:01
I think I might have run into this issue. I was getting a `Curl is configured to use SSL, but we have not been able to determine which SSL backend it is using. Please see PycURL documentation for how to specify the SSL backend manually.` error on [this line](https://github.com/villasv/aws-airflow-stack/blob/master/templates/turbine-cluster.template#L504).

Adding `PYCURL_SSL_LIBRARY=openssl` at the beginning of that line helped.

**Comment by villasv** [comment] 2020-03-12 16:34
Thanks for helping @bayarmunkh! Could you tell me which region are you using? I'm suspecting that the AMIs used for some regions are not really equivalent.

> Adding PYCURL_SSL_LIBRARY=openssl at the beginning of that line helped.

That's strange, the command to install `pycurl` is in the line right above and it has the SSL_LIBRARY flag.

**Comment by bayarmunkh** [comment] 2020-03-12 17:08
i'm using us-east-1.

**Comment by villasv** [comment] 2020-03-13 15:26
Weird. I was not able to reproduce the deployment error using the launch button and in us-east-1. I'll investigate the pycurl thing later on, but since I could not reproduce and I couldn't get more info from @Monikatak, I'll close this issue.

Maybe they just forgot to provide a password for RDS?

**Closed as completed** 2020-03-13 15:27 UTC
Labels: investigate

**Comment by villasv** [comment] 2020-03-13 20:02
I have confirmed the pycurl issue (https://github.com/villasv/aws-airflow-stack/issues/160). It looks like the pinned version is different from the one installed manually so the install command has to be different. Thanks for reporting @bayarmunkh
